//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogsParser.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogsParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1001	Max HP Boost
        ///1002	Max MP Boost
        ///1003	HP Regen Boost
        ///1004	HP Recovery Boost
        ///1005	MP Regen Boost
        ///1006	MP Recovery Boost
        ///1007	P. Attack Boost
        ///1008	M. Power Boost
        ///1009	P. Defense Boost
        ///1010	Magical Defense Power increases
        ///1011	Attack Speed Boost
        ///1012	Cast Speed Boost
        ///1013	Move Speed Boost
        ///1014	Accuracy Boost
        ///1015	Evasion Boost
        ///1016	M. Accuracy Boost
        ///1017	M. Res increases
        ///1018	Crit Chance Boost
        ///1019	Crit Power Boost
        ///1021	Block Per Boost
        ///1051	Hidden Village Attack Power increases
        ///1052	Hidden Village Magical P [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string buffs {
            get {
                return ResourceManager.GetString("buffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Xijezu.
        /// </summary>
        internal static string characters {
            get {
                return ResourceManager.GetString("characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GM_ToolBlue {
            get {
                object obj = ResourceManager.GetObject("GM_ToolBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GM_ToolBlueAbout {
            get {
                object obj = ResourceManager.GetObject("GM_ToolBlueAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GM_ToolRed {
            get {
                object obj = ResourceManager.GetObject("GM_ToolRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GM_ToolRedAbout {
            get {
                object obj = ResourceManager.GetObject("GM_ToolRedAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 101331	Souleating Blade
        ///101531	Parasitic Blade
        ///101731	Flesheating Blade
        ///102331	Greatsword of Fury
        ///102531	Greatsword of Bloodrage
        ///102731	Greatsword of Obliteration
        ///103331	Twisted Barb
        ///103531	Shadowmage Barb
        ///103731	Dimensional Barb
        ///104331	Flameburst Spear
        ///104531	Mankiller Spear
        ///104731	Leon&apos;s Glory
        ///105331	Alloy Greataxe
        ///105531	Horizon&apos;s Edge
        ///105731	Hector&apos;s Greataxe
        ///106331	Smiter
        ///106531	Windbreaker
        ///106731	The Silencer
        ///107331	Kaia&apos;s Blessing
        ///107531	Hammer of Justice
        ///107731	Mace of Learning
        ///108331	Longshot Bow
        ///1 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimize3 {
            get {
                object obj = ResourceManager.GetObject("Minimize3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1	White Dragon Lv 1
        ///2	Bloodymos1
        ///3	Brain Slater1
        ///4	Clay Beast1
        ///5	Deva Priest
        ///6	Asura Priest
        ///7	Gaia Priest
        ///8	Ashmaw the Devourer
        ///9	Sand Lord Kynish
        ///10	Koala
        ///11	Lucky Koala
        ///12	Mystic Koala
        ///13	PrimalScream1
        ///14	Crustalino Test
        ///15	Bone Temple Guard
        ///16	Location of Crystal
        ///17	Unicorn Lv 3
        ///18	Dark Sachar
        ///19	White Wolf
        ///20	Cruelty Bashal
        ///21	Black Dragon
        ///22	Green Dragon
        ///23	Dun Fear
        ///24	ÅØ½ºÃ³Å×½ºÆ®
        ///25	Betrayal
        ///26	Liquidlust
        ///27	Bone Temple Guard
        ///28	Location of Crystal
        ///29	Guardian Angel
        ///30	Infernal Lapika
        ///31	Windsong Lv  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string monster {
            get {
                return ResourceManager.GetString("monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon MXRed {
            get {
                object obj = ResourceManager.GetObject("MXRed", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 60	Creature test01
        ///61	Creature test02
        ///62	Creature test03
        ///63	Creature test04
        ///64	Creature test05
        ///65	Creature test06
        ///1001	Ornitho&lt;For rent only&gt;
        ///1002	Lydian&lt;Hidden Village&gt;
        ///1003	Ornitho&lt;Hidden Village&gt;
        ///1004	Purple Ornitho
        ///1005	Red Ornitho
        ///1006	Red Lydian
        ///1007	Blue Lydian
        ///1008	Red Lydian&lt;event&gt;
        ///1009	Blue Lydian&lt;event&gt;
        ///1010	White Tiger
        ///1011	Fiery Pixie
        ///1021	Water Pixie
        ///1201	Hawkman
        ///1301	Siren Child
        ///1401	Ent
        ///1501	White Dragon
        ///1601	Astarot
        ///1701	Junior Kenta
        ///1801	Yeti Thoth
        ///1901	Petite Salamander
        ///2001	Purity Angel
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string pets {
            get {
                return ResourceManager.GetString("pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Resize3 {
            get {
                object obj = ResourceManager.GetObject("Resize3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 152465	76951	Horizon
        ///151896	72599	Horizon Arena
        ///139369	73704	Witch
        ///132995	87096	Moonlight 1
        ///130842	79586	Moonlight 2
        ///155817	103724	Lost Mines 1
        ///152309	102886	Lost Mines 2
        ///117974	59119	Katan
        ///7363	7101	Laksy
        ///135876	156035	Fairy&apos;s Woods
        ///142086	132207	Siren Island
        ///138174	105965	Rondo
        ///159712	124736	Beginning of Marduka
        ///162624	131811	Mare Village
        ///211302	129971	Palmir Plateau 1
        ///211299	146193	Palmir Plateau 2
        ///103210	100366	CV1
        ///99757	103236	CV2
        ///154666	150287	City of Ruins
        ///83876	115913	Veiled Island
        ///201400	151566	Tem [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string warplist {
            get {
                return ResourceManager.GetString("warplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Worldmap {
            get {
                object obj = ResourceManager.GetObject("Worldmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
